run verilator first in CI to get desired results faster in case of e.g. limited agents

diff --git a/.buildkite/ci.yml b/.buildkite/ci.yml
--- a/.buildkite/ci.yml
+++ b/.buildkite/ci.yml
@@ -43,6 +43,31 @@ steps:
 
 - wait: { continue_on_failure: true }
 
+- label: ":wrench: Verilator"
+  agents:
+    docker: "true"
+  commands:
+
+  # In case prior step failed to clean up correctly
+  - docker ps
+  - docker kill $VCONTAINER || true
+  # Sometimes it takes a second to die...
+  - sleep 10
+  - docker ps
+
+  - docker run -id --name $VCONTAINER --rm -v /cad:/cad $IMAGE bash
+  - docker exec $VCONTAINER /bin/bash -c "rm -rf /aha/garnet"
+  - docker cp . $VCONTAINER:/aha/garnet
+
+  # For quick test of verilator-compatible code, remove "echo if TEST" below
+  - docker exec $VCONTAINER /bin/bash -c "
+      source /aha/bin/activate;
+      source /cad/modules/tcl/init/sh;
+      echo '+++SETUP';
+      make -f garnet/tests/test_app/Makefile verilator-setup;
+      echo '+++POINTWISE TEST';
+      make -f garnet/tests/test_app/Makefile pointwise
+    "
 
 - label: ":wrench: Aha regressions"
   agents:
@@ -68,32 +93,6 @@ steps:
       echo if TEST cp garnet/tests/test_app/dev/verilator-test.regress.py aha/util/regress.py;
       echo aha regress pr;
       pwd; aha regress pr;
-    "
-
-- label: ":wrench: Verilator"
-  agents:
-    docker: "true"
-  commands:
-
-  # In case prior step failed to clean up correctly
-  - docker ps
-  - docker kill $VCONTAINER || true
-  # Sometimes it takes a second to die...
-  - sleep 10
-  - docker ps
-
-  - docker run -id --name $VCONTAINER --rm -v /cad:/cad $IMAGE bash
-  - docker exec $VCONTAINER /bin/bash -c "rm -rf /aha/garnet"
-  - docker cp . $VCONTAINER:/aha/garnet
-
-  # For quick test of verilator-compatible code, remove "echo if TEST" below
-  - docker exec $VCONTAINER /bin/bash -c "
-      source /aha/bin/activate;
-      source /cad/modules/tcl/init/sh;
-      echo '+++SETUP';
-      make -f garnet/tests/test_app/Makefile verilator-setup;
-      echo '+++POINTWISE TEST';
-      make -f garnet/tests/test_app/Makefile pointwise
     "
 
 # ALWAYS clean up regardless of test success or failure
