Revert "cts happens *after* placement. who knew?"
This reverts commit 35d89f7666b5ca8dcd196c92b3212ea41b6b8831.

diff --git a/.buildkite/pipeline_fullchip.yml b/.buildkite/pipeline_fullchip.yml
--- a/.buildkite/pipeline_fullchip.yml
+++ b/.buildkite/pipeline_fullchip.yml
@@ -95,18 +95,18 @@ steps:
      echo exit 13 | make cadence-genus-synthesis |& tee make-syn.log'
 - wait: ~
 
-- label: 'place'
-  commands:
-  - 'source mflowgen/bin/setup-buildkite.sh --dir $$GOLD --need_space 71G;
-     echo "--- MAKE CADENCE-INNOVUS-PLACE"; set -o pipefail;
-     echo exit 13 | make cadence-innovus-place |& tee make-place.log'
-- wait: ~
-
 - label: 'cts'
   commands:
   - 'source mflowgen/bin/setup-buildkite.sh --dir $$GOLD --need_space 71G;
      echo "--- MAKE CADENCE-INNOVUS-CTS"; set -o pipefail;
      echo exit 13 | make cadence-innovus-cts |& tee make-cts.log'
+- wait: ~
+
+- label: 'place'
+  commands:
+  - 'source mflowgen/bin/setup-buildkite.sh --dir $$GOLD --need_space 71G;
+     echo "--- MAKE CADENCE-INNOVUS-PLACE"; set -o pipefail;
+     echo exit 13 | make cadence-innovus-place |& tee make-place.log'
 - wait: ~
 
 - label: 'route'
