maybe i got the rtl build wrong?

diff --git a/.buildkite/pipelines/glb_top.yml b/.buildkite/pipelines/glb_top.yml
--- a/.buildkite/pipelines/glb_top.yml
+++ b/.buildkite/pipelines/glb_top.yml
@@ -18,53 +18,60 @@ steps:
      echo "$stepname"; echo "2 $$stepname";
      echo 3 $stepname; echo 4 $$stepname;
 
-     source mflowgen/bin/setup-buildkite.sh --dir $$GOLD --need_space 10G;
+     source mflowgen/bin/setup-buildkite.sh --dir $$GOLD --need_space 1G;
      mflowgen run --design $$GARNET_HOME/mflowgen/full_chip;
      set -x;
      grep mem_size  $$GARNET_HOME/mflowgen/glb_top/construct.py;
      grep mem_size .mflowgen/*glb_top/configure.yml;
      grep mem_size -r .mflowgen;
-
-     # Quick check of the flow graph
-
-     : "Build glb_top subdir using appropriate numbering scheme";
-     stepname=$(cd .mflowgen; /bin/ls -d *glb_top | head -1);
-     mkdir -p $$stepname; cd $$stepname;     
-     mflowgen run --design $$GARNET_HOME/mflowgen/glb_top;
-
-     : "Early early out if e.g. missing input edges";
-     $$GARNET_HOME/mflowgen/bin/find-unmatched-inputs.sh .mflowgen/graph.dot || exit 13;
      '
-
 - wait: ~
 
 
+#      # Quick check of the flow graph
+# 
+#      : "Build glb_top subdir using appropriate numbering scheme";
+#      stepname=$(cd .mflowgen; /bin/ls -d *glb_top | head -1);
+#      mkdir -p $$stepname; cd $$stepname;     
+#      mflowgen run --design $$GARNET_HOME/mflowgen/glb_top;
+# 
+#      : "Early early out if e.g. missing input edges";
+#      $$GARNET_HOME/mflowgen/bin/find-unmatched-inputs.sh .mflowgen/graph.dot || exit 13;
 
-# Build RTL from scratch
-- label: 'rtl'
+
+- label: 'full_chip rtl'
   commands:
-  - 'source mflowgen/bin/setup-buildkite.sh --dir $$GOLD --need_space 10G;
-     foo=$(echo bar); echo $$foo;
+  - 'source mflowgen/bin/setup-buildkite.sh --dir $$GOLD --need_space 1G;
      echo "--- MAKE RTL"; set -o pipefail;
      make rtl |& tee make-rtl.log'
 - wait: ~
 
-
-
-- label: 'glb_tile'
+- label: 'glb_top rtl'
   commands:
   - '
-     : "Set up env and cd to GOLD (ffull_chip) dir";
-     echo "--- MAKE GLB_TILE"; set -o pipefail;
-     source mflowgen/bin/setup-buildkite.sh --dir $$GOLD --need_space 10G;
+     : "Set up env and cd to GOLD (full_chip) dir";
+     echo "--- GLB_TOP setup"; set -o pipefail;
+     source mflowgen/bin/setup-buildkite.sh --dir $$GOLD --need_space 1G;
 
-     : "Build glb_top subdir using appropriate numbering scheme";
+     echo "--- Build glb_top subdir using appropriate numbering scheme";
      stepname=$(cd .mflowgen; /bin/ls -d *glb_top | head -1);
      mkdir -p $$stepname; cd $$stepname;     
      mflowgen run --design $$GARNET_HOME/mflowgen/glb_top;
 
-     : "Early out if e.g. missing sram.spi input edge";
+     echo "--- Early out if e.g. missing sram.spi input edge";
      $$GARNET_HOME/mflowgen/bin/find-unmatched-inputs.sh .mflowgen/graph.dot || exit 13;
+
+     echo "--- MAKE RTL"; set -o pipefail;
+     make rtl |& tee make-rtl.log'
+- wait: ~
+
+- label: 'glb_tile'
+  commands:
+  - '
+     : "Set up env and cd to GOLD/glb_top dir";
+     echo "--- MAKE GLB_TILE"; set -o pipefail;
+     source mflowgen/bin/setup-buildkite.sh --dir $$GOLD --need_space 1G;
+     cd *-glb_top;
 
      : "Build the tile";
      echo exit 13 | make glb_tile |& tee make-glb_tile.log;
@@ -75,11 +82,11 @@ steps:
   - '
      : Set up env and cd to GOLD (full_chip) dir
      echo "--- MAKE GLB_TOP"; set -o pipefail;
-     source mflowgen/bin/setup-buildkite.sh --dir $$GOLD --need_space 10G;
+     source mflowgen/bin/setup-buildkite.sh --dir $$GOLD --need_space 1G;
 
      : Build everything up through LVS
      cd *-glb_top;
-     echo exit 13 | make mentor-calibre-lbs |& tee make-lvs.log;
+     echo exit 13 | make mentor-calibre-lvs |& tee make-lvs.log;
 
      : Double check to make sure nothing failed!
      echo "egrep ^FAILED make-*.log && exit 13";
