cleanup

diff --git a/.buildkite/pipelines/pmg.yml b/.buildkite/pipelines/pmg.yml
--- a/.buildkite/pipelines/pmg.yml
+++ b/.buildkite/pipelines/pmg.yml
@@ -39,6 +39,24 @@ steps:
   - docker pull stanfordaha/garnet:latest
 - wait
 
+
+
+#####################################################################################
+# Two quick RTL checks. Set soft fail so RTL failure does not fail integration tests.
+
+# Turning off amber because I think it has lost its way completely at this point...
+# - label: "Gold RTL: Amber 1m"
+#   soft_fail: true
+#   commands:
+#   - 'bin/rtl-goldcheck.sh --use-docker $$IMAGE $$CONTAINER amber'
+
+- label: "Gold RTL: Onyx 1m"
+  soft_fail: true
+  commands:
+  - 'bin/rtl-goldcheck.sh --use-docker $$IMAGE $$CONTAINER onyx'
+
+- wait: { continue_on_failure: true }
+
 ##############################################################################
 # INDIVIDUAL TILE RUNS
 # Builds in dir e.g. mflowgen/full_chip/19-tile_array/17-Tile_PE
@@ -46,8 +64,7 @@ steps:
 # Default is to run three tile tests (PE, Mem, GLB) up through
 # floorplanning (init), which should take about 20-30 minutes.
 
-# ------------------------------------------------------------------------
-# PTILE through cts
+# PTILE through init
 # Set pe max width to 112: fp limits to 110 but then lvs says 112 OK
 - label: 'ptile init 20m'
   commands:
@@ -55,25 +72,20 @@ steps:
      echo "--- BEGIN mflowgen run";
      mflowgen run --design $$GARNET_HOME/mflowgen/full_chip;
      echo "--- BEGIN make init";
-     echo make tile_array-Tile_PE-mentor-calibre-lvs;
-     echo exit 13 | make tile_array-Tile_PE-mentor-calibre-lvs;'
+     echo make tile_array-Tile_PE-cadence-innovus-init;
+     echo exit 13 | make tile_array-Tile_PE-cadence-innovus-init;'
   - .buildkite/pipelines/check_tile_width.sh Tile_PE --max 112 $BDIR
   - mflowgen/bin/buildcheck.sh $BDIR/full_chip/*tile_array/*Tile_PE --show-all-errors
 
-# MTILE through lvs
-- label: 'mtile lvs 2h'
+# MTILE through init
+- label: 'mtile init 25m'
   commands:
   - 'source mflowgen/bin/setup-buildkite.sh $$SETUP_FLAGS;
      echo "--- BEGIN mflowgen run";
      mflowgen run --design $$GARNET_HOME/mflowgen/full_chip;
      echo "--- BEGIN make init";
-
-     echo make tile_array-Tile_MemCore-mentor-calibre-lvs;
-     echo exit 13 | make tile_array-Tile_MemCore-mentor-calibre-lvs;
-
-     # echo make tile_array-Tile_MemCore-mentor-calibre-lvs;
-     # echo exit 13 | make tile_array-Tile_MemCore-mentor-calibre-lvs;'
-
+     echo make tile_array-Tile_MemCore-cadence-innovus-init;
+     echo exit 13 | make tile_array-Tile_MemCore-cadence-innovus-init;'
   - .buildkite/pipelines/check_tile_width.sh Tile_MemCore --max 250 $BDIR
   - mflowgen/bin/buildcheck.sh $BDIR/full_chip/*tile_array/*Tile_MemCore --show-all-errors
 
@@ -84,7 +96,7 @@ steps:
      echo "--- BEGIN mflowgen run";
      mflowgen run --design $$GARNET_HOME/mflowgen/full_chip;
      echo "--- BEGIN make init";
-     echo make glb_top-glb_tile-mentor-calibre-lvs;
-     echo exit 13 | make glb_top-glb_tile-mentor-calibre-lvs;'
+     echo make glb_top-glb_tile-cadence-innovus-init;
+     echo exit 13 | make glb_top-glb_tile-cadence-innovus-init;'
   - mflowgen/bin/buildcheck.sh $BDIR/full_chip/*glb_top/*glb_tile --show-all-errors
 
