temporarily simplify mflowgen CI test

diff --git a/.buildkite/pipelines/pmg.yml b/.buildkite/pipelines/pmg.yml
--- a/.buildkite/pipelines/pmg.yml
+++ b/.buildkite/pipelines/pmg.yml
@@ -38,17 +38,17 @@ steps:
 ##############################################################################
 # Two quick RTL checks
 
-- label: "Gold RTL: Amber 1m"
-  commands:
-  - '
-     docker pull $$IMAGE; container=$$CONTAINER-amber;
-     docker run -id --name $$container --rm -v /cad:/cad $$IMAGE bash;
-     function dexec { docker exec $$container /bin/bash -c "$$*"; };
-     dexec "rm -rf /aha/garnet"; docker cp . $$container:/aha/garnet;
-     dexec "/aha/garnet/bin/rtl-goldcheck.sh amber" || $$FAIL_AMBER | $$UPLOAD;
-     docker image prune -f -a;
-     docker kill $$container || echo cannot kill container;
-    '
+# - label: "Gold RTL: Amber 1m"
+#   commands:
+#   - '
+#      docker pull $$IMAGE; container=$$CONTAINER-amber;
+#      docker run -id --name $$container --rm -v /cad:/cad $$IMAGE bash;
+#      function dexec { docker exec $$container /bin/bash -c "$$*"; };
+#      dexec "rm -rf /aha/garnet"; docker cp . $$container:/aha/garnet;
+#      dexec "/aha/garnet/bin/rtl-goldcheck.sh amber" || $$FAIL_AMBER | $$UPLOAD;
+#      docker image prune -f -a;
+#      docker kill $$container || echo cannot kill container;
+#     '
 
 - label: "Gold RTL: Onyx 1m"
   commands:
@@ -63,90 +63,90 @@ steps:
     '
 - wait: { continue_on_failure: true }
 
-##############################################################################
-# INDIVIDUAL TILE RUNS
-# Builds in dir e.g. mflowgen/full_chip/19-tile_array/17-Tile_PE
-
-# Default is to run three tile tests (PE, Mem, GLB) up through
-# floorplanning (init), which should take about 20-30 minutes.
-
-# ------------------------------------------------------------------------
-
-# PTILE through init
-# Set pe max width to 112: fp limits to 110 but then lvs says 112 OK
-- label: 'ptile init 20m'
-  commands:
-  - 'source mflowgen/bin/setup-buildkite.sh $$SETUP_FLAGS;
-     echo "--- BEGIN mflowgen run";
-     mflowgen run --design $$GARNET_HOME/mflowgen/full_chip;
-     echo "--- BEGIN make init";
-     echo make tile_array-Tile_PE-cadence-innovus-init;
-     echo exit 13 | make tile_array-Tile_PE-cadence-innovus-init;'
-  - .buildkite/pipelines/check_tile_width.sh Tile_PE --max 112 $BDIR
-  - mflowgen/bin/buildcheck.sh $BDIR/full_chip/*tile_array/*Tile_PE --show-all-errors
-
-# PTILE through LVS
-# - label: 'ptile lvs 2h'
+# ##############################################################################
+# # INDIVIDUAL TILE RUNS
+# # Builds in dir e.g. mflowgen/full_chip/19-tile_array/17-Tile_PE
+# 
+# # Default is to run three tile tests (PE, Mem, GLB) up through
+# # floorplanning (init), which should take about 20-30 minutes.
+# 
+# # ------------------------------------------------------------------------
+# 
+# # PTILE through init
+# # Set pe max width to 112: fp limits to 110 but then lvs says 112 OK
+# - label: 'ptile init 20m'
 #   commands:
-#   - $TEST --need_space 30G full_chip tile_array Tile_PE --steps mentor-calibre-lvs --debug
+#   - 'source mflowgen/bin/setup-buildkite.sh $$SETUP_FLAGS;
+#      echo "--- BEGIN mflowgen run";
+#      mflowgen run --design $$GARNET_HOME/mflowgen/full_chip;
+#      echo "--- BEGIN make init";
+#      echo make tile_array-Tile_PE-cadence-innovus-init;
+#      echo exit 13 | make tile_array-Tile_PE-cadence-innovus-init;'
 #   - .buildkite/pipelines/check_tile_width.sh Tile_PE --max 112 $BDIR
 #   - mflowgen/bin/buildcheck.sh $BDIR/full_chip/*tile_array/*Tile_PE --show-all-errors
-#   if: build.branch !~ /to-spv/ && build.branch !~ /spV/
-
-# ------------------------------------------------------------------------
-
-# MTILE through init
-- label: 'mtile init 25m'
-  commands:
-  - 'source mflowgen/bin/setup-buildkite.sh $$SETUP_FLAGS;
-     echo "--- BEGIN mflowgen run";
-     mflowgen run --design $$GARNET_HOME/mflowgen/full_chip;
-     echo "--- BEGIN make init";
-     echo make tile_array-Tile_MemCore-cadence-innovus-init;
-     echo exit 13 | make tile_array-Tile_MemCore-cadence-innovus-init;'
-  - .buildkite/pipelines/check_tile_width.sh Tile_MemCore --max 250 $BDIR
-  - mflowgen/bin/buildcheck.sh $BDIR/full_chip/*tile_array/*Tile_MemCore --show-all-errors
-
-# MTILE through LVS
-# - label: 'mtile lvs 2h'
+# 
+# # PTILE through LVS
+# # - label: 'ptile lvs 2h'
+# #   commands:
+# #   - $TEST --need_space 30G full_chip tile_array Tile_PE --steps mentor-calibre-lvs --debug
+# #   - .buildkite/pipelines/check_tile_width.sh Tile_PE --max 112 $BDIR
+# #   - mflowgen/bin/buildcheck.sh $BDIR/full_chip/*tile_array/*Tile_PE --show-all-errors
+# #   if: build.branch !~ /to-spv/ && build.branch !~ /spV/
+# 
+# # ------------------------------------------------------------------------
+# 
+# # MTILE through init
+# - label: 'mtile init 25m'
 #   commands:
-#   - $TEST --need_space 30G full_chip tile_array Tile_MemCore --steps mentor-calibre-lvs --debug
+#   - 'source mflowgen/bin/setup-buildkite.sh $$SETUP_FLAGS;
+#      echo "--- BEGIN mflowgen run";
+#      mflowgen run --design $$GARNET_HOME/mflowgen/full_chip;
+#      echo "--- BEGIN make init";
+#      echo make tile_array-Tile_MemCore-cadence-innovus-init;
+#      echo exit 13 | make tile_array-Tile_MemCore-cadence-innovus-init;'
 #   - .buildkite/pipelines/check_tile_width.sh Tile_MemCore --max 250 $BDIR
 #   - mflowgen/bin/buildcheck.sh $BDIR/full_chip/*tile_array/*Tile_MemCore --show-all-errors
-
-# ------------------------------------------------------------------------
-
-# GTILE through init
-- label: 'gtile init 20m'
-  commands:
-  - 'source mflowgen/bin/setup-buildkite.sh $$SETUP_FLAGS;
-     echo "--- BEGIN mflowgen run";
-     mflowgen run --design $$GARNET_HOME/mflowgen/full_chip;
-     echo "--- BEGIN make init";
-     echo make glb_top-glb_tile-cadence-innovus-init;
-     echo exit 13 | make glb_top-glb_tile-cadence-innovus-init;'
-  - mflowgen/bin/buildcheck.sh $BDIR/full_chip/*glb_top/*glb_tile --show-all-errors
-
-# GTILE through LVS
-# - label: 'gtile lvs 3h'
+# 
+# # MTILE through LVS
+# # - label: 'mtile lvs 2h'
+# #   commands:
+# #   - $TEST --need_space 30G full_chip tile_array Tile_MemCore --steps mentor-calibre-lvs --debug
+# #   - .buildkite/pipelines/check_tile_width.sh Tile_MemCore --max 250 $BDIR
+# #   - mflowgen/bin/buildcheck.sh $BDIR/full_chip/*tile_array/*Tile_MemCore --show-all-errors
+# 
+# # ------------------------------------------------------------------------
+# 
+# # GTILE through init
+# - label: 'gtile init 20m'
 #   commands:
-#   - $TEST --need_space 30G full_chip glb_top glb_tile --steps mentor-calibre-lvs --debug
+#   - 'source mflowgen/bin/setup-buildkite.sh $$SETUP_FLAGS;
+#      echo "--- BEGIN mflowgen run";
+#      mflowgen run --design $$GARNET_HOME/mflowgen/full_chip;
+#      echo "--- BEGIN make init";
+#      echo make glb_top-glb_tile-cadence-innovus-init;
+#      echo exit 13 | make glb_top-glb_tile-cadence-innovus-init;'
 #   - mflowgen/bin/buildcheck.sh $BDIR/full_chip/*glb_top/*glb_tile --show-all-errors
-
-# ------------------------------------------------------------------------
-
-# GTOP through LVS
-# - label: 'gtop lvs 3h?'
-#   commands:
-#   - $TEST --need_space 30G full_chip glb_top --steps mentor-calibre-lvs --debug
-#   - mflowgen/bin/buildcheck.sh $BDIR/full_chip/*glb_top --show-all-errors
-
-# ------------------------------------------------------------------------
-
-# ONYX BRANCHES ONLY
-# GF branches cannot run synthesis on my machine, so do RTL only I guess
-# - label: 'RTL only 25m'
-#   commands:
-#   - 'export WHICH_SOC=onyx;
-#     $TEST --need_space 30G full_chip --steps rtl --debug'
-#   if: build.branch =~ /to-spv/ || build.branch =~ /spV/ || build.branch =~ /sms/
+# 
+# # GTILE through LVS
+# # - label: 'gtile lvs 3h'
+# #   commands:
+# #   - $TEST --need_space 30G full_chip glb_top glb_tile --steps mentor-calibre-lvs --debug
+# #   - mflowgen/bin/buildcheck.sh $BDIR/full_chip/*glb_top/*glb_tile --show-all-errors
+# 
+# # ------------------------------------------------------------------------
+# 
+# # GTOP through LVS
+# # - label: 'gtop lvs 3h?'
+# #   commands:
+# #   - $TEST --need_space 30G full_chip glb_top --steps mentor-calibre-lvs --debug
+# #   - mflowgen/bin/buildcheck.sh $BDIR/full_chip/*glb_top --show-all-errors
+# 
+# # ------------------------------------------------------------------------
+# 
+# # ONYX BRANCHES ONLY
+# # GF branches cannot run synthesis on my machine, so do RTL only I guess
+# # - label: 'RTL only 25m'
+# #   commands:
+# #   - 'export WHICH_SOC=onyx;
+# #     $TEST --need_space 30G full_chip --steps rtl --debug'
+# #   if: build.branch =~ /to-spv/ || build.branch =~ /spV/ || build.branch =~ /sms/
