pipe no parse 2345

diff --git a/.buildkite/pipelines/pmtile_synth_only.yml b/.buildkite/pipelines/pmtile_synth_only.yml
--- a/.buildkite/pipelines/pmtile_synth_only.yml
+++ b/.buildkite/pipelines/pmtile_synth_only.yml
@@ -49,3 +49,81 @@ steps:
      '
 
 - wait: ~
+
+- label: 'PE'
+  commands:
+  - '
+     echo "--- SETUP";
+     source mflowgen/bin/setup-buildkite.sh --dir $$FC;
+     cd *-tile_array/*-Tile_PE;
+     set -o pipefail;
+
+     echo "--- MAKE RTL";
+     make rtl |& tee make-rtl.log;
+
+     echo "--- MAKE SYNTH";
+     make synth |& tee make-synth.log;
+
+     echo "--- MAKE INIT";
+     make init |& tee make-init.log;
+     '
+
+- label: 'MemCore'
+  commands:
+  - '
+     echo "--- SETUP";
+     source mflowgen/bin/setup-buildkite.sh --dir $$FC;
+     cd *-tile_array/*-Tile_MemCore;
+     set -o pipefail;
+
+     echo "--- MAKE RTL";
+     make rtl |& tee make-rtl.log;
+
+     echo "--- MAKE SYNTH";
+     make synth |& tee make-synth.log;
+
+     echo "--- MAKE INIT";
+     make init |& tee make-init.log;
+     '
+
+- label: 'GLB'
+  commands:
+  - '
+     echo "--- SETUP";
+     source mflowgen/bin/setup-buildkite.sh --dir $$FC;
+     cd *-tile_array/*-glb_top;
+     set -o pipefail;
+
+     echo "--- MAKE RTL";
+     make rtl |& tee make-rtl.log;
+
+     echo "--- MAKE SYNTH";
+     make synth |& tee make-synth.log;
+
+     echo "--- MAKE INIT";
+     make init |& tee make-init.log;
+     '
+
+# Wait for all three tests to finish
+- wait: { continue_on_failure: true }
+
+
+# Final check for errors and such
+- label: 'CHECK'
+  commands:
+  - set -x; ls -l $FC
+  - set -x; find $FC -name genus.log -exec -exec grep 'Cannot resolve' {} \;
+  - set -x; mflowgen/bin/buildcheck.sh $FC --show-all-errors
+
+# Wait for all three tests to finish
+- wait: { continue_on_failure: true }
+
+- label: 'CLEANUP'
+  commands:
+  - set -x; ls -l /sim/buildkite-agent/deleteme/CI${BUILDKITE_BUILD_NUMBER}
+  - set -x; /bin/rm -rf /sim/buildkite-agent/deleteme/CI${BUILDKITE_BUILD_NUMBER}
+  - set -x; ls -l /sim/buildkite-agent/deleteme/CI${BUILDKITE_BUILD_NUMBER} || echo pass
+
+# TODO/FIXME delete all deleteme subdirs older than 1 hour
+
+
